export const RouteIndex = "/"
export const RouteSignIn = "/signin"
export const RouteSignUp = "/signup"
export const RouteProfile = "/profile"
export const RouteCategoryDetails = "/categories"
export const RouteAddCategory = "/category/add"
export const RouteEditCategory = "/category/edit/:id"

export const RouteBlog = "/blog"
export const RouteBlogAdd = "/blog/add"
export const RouteBlogEdit = "/blog/edit/:id"
export const RouteBlogDetails = "/blog/details/:id"
